name: dotnet build and push docker image for the supplied architecture
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
      architecture:
        required: true
        type: choice
        options:
        - amd64
        - arm64

jobs:
  build:
    name: Build and publish docker image
    uses: ./.github/workflows/dotnet_shared_multi-architecture-build-and-test.yml
    with:
      image-name: ${{ inputs.image-name }}
      architecture: ${{ inputs.architecture }}
      run-unit-tests: false
      build-image: true
      version: ${{ inputs.version }}
    secrets: inherit
