name: Unit test and create new release
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  unit-test:
    name: Run unit tests
    uses: ./.github/workflows/_shared_multi-architecture-dotnet-build-and-test.yml
    with:
      image-name: ${{ inputs.image-name }}
      architecture: amd64
      run-unit-tests: true
      build-image: false
    secrets: inherit
  
  create-release:
    name: Create release
    needs: [unit-test]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.25.0
        with:
          bump_version_scheme: patch
          # Remove the "v" prefix, so we just get major.minor.patch
          tag_prefix: ""
