name: Build arm64 Docker Image
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    name: Build and publish docker image
    uses: ./.github/workflows/_shared_multi-architecture-dotnet-build-and-test.yml
    with:
      image-name: ${{ inputs.image-name }}
      architecture: arm64
      run-unit-tests: false
      build-image: true
      version: ${{ inputs.version }}
    secrets: inherit
